name: permission_handler_windows
publish_to: none
description: Permission plugin for Flutter. This plugin provides the Windows API to request and check permissions.
version: 0.1.3
homepage: https://github.com/baseflow/flutter-permission-handler

flutter:
  plugin:
    implements: permission_handler
    platforms:
      windows:
        pluginClass: PermissionHandlerWindowsPlugin

dependencies:
  flutter:
    sdk: flutter
  permission_handler_platform_interface: 
    git: https://github.com/kumsumit/permission_handler_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: 
    git: https://github.com/kumsumit/plugin_platform_interface.git

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"
